flyway.url=jdbc:postgresql://localhost:5432/chessdb
flyway.schemas=public
flyway.user=root
flyway.password=password
flyway.locations=filesystem:./src/main/resources/db/migrations
flyway.cleanDisabled=false
flyway.validateMigrationNaming=true
