spring.application.name=chess-platform
# enable virtual thread
spring.threads.virtual.enabled=true
# servlet settings
server.port=${SERVER_PORT:8080}
# current active profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
# database settings
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/chessdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=validate
# logging settings
spring.main.banner-mode=off
logging.level.root=warn
logging.level.me.zilid.chessplatform=info
