# database settings
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# redis settings
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
# actuator settings
management.server.port=${MANAGEMENT_SERVER_PORT:9090}
management.endpoints.web.exposure.include=health,info,metrics
# OpenAPI settings
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false
# logging settings
logging.level.root=warn
logging.level.me.zilid.chessplatform=info
